version: '3.5'

services:
  urhalaphp:
    build:
      context: ./
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        uid: ${UID:-1000}
    container_name: urhalaphp-${BRANCH}
    depends_on:
      - urhaladb
    volumes:
      - .:/var/www/urhala
      - ./docker/php-fpm/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks: 
      - urhala
  
  urhalanginx:
    container_name: urhalanginx-${BRANCH}
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
      args:
        branch: ${BRANCH}
    depends_on:
      - urhaladb
    volumes:
      - .:/var/www/urhala
    ports:
      - ${API_PORT}:80
    networks:
      - urhala

  urhaladb:
    container_name: urhaladb-${BRANCH}
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
      args:
        db_username: ${DB_USERNAME}
        db_rootpass: ${DB_ROOTPASSWORD}
    command: mysqld --general-log=1 --general-log-file=/var/log/mysql/general-log.log --default-authentication-plugin=mysql_native_password
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOTPASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - urhala

  urhalaphpmyadmin:
    depends_on:
      - urhaladb
    image: phpmyadmin:latest
    container_name: urhalaphpmyadmin-${BRANCH}
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: urhaladb
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
    networks:
      - urhala

networks:
  urhala:
volumes:
  data: